---

- name: MongoDB delete key first
  apt_key:
    keyserver: http://keyserver.ubuntu.com:80
    state: absent 
    id: 91FA4AD5

- name: MOngoDB - Import public key
#  apt_key:
#    keyserver: http://keyserver.ubuntu.com:80
#    id: 0C49F3730359A14518585931BC711F9BA15703C6
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

- name: MongoDB - Add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-3.4.list'
    repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse'
    state: present
    update_cache: yes

- name: MongoDB - Install MongoDB
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mongodb-org
    - mongodb-org-server
    - bc
    - python-pip
#    - mongodb-client

- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory mode=0755 

- name: create log directory for mongodb
  file: path=/var/log/mongo state=directory owner=mongod group=mongod mode=0644

#- name: Install the latest pymongo package
#  pip: name=pymongo state=latest use_mirorrs=no

- name: install systemd service
  copy:
    src=mongod.service
    dest=/etc/systemd/system/mongod.service
- name: MongoDB - Running state
  service:
    name: mongod
    state: started
