
---
# Secure replication using the secret
- name: Copy the keyfile for replicated authentication
  copy: src=secret dest={{ mongodb_datadir_prefix }}secret owner=mongod group=mongod mode=0400

- name: Create the authenticated mongodb configuration file
  template: src=~/mongo_ha/playbook/roles/mongod_replicaset/templates/mongod.conf.j2 dest=/etc/mongod.conf

- name: Restart mongodb
  service: name=mongod enabled=yes state=restarted

- name: Create the file to initialize the replicaset
  template: src=~/mongo_ha/playbook/roles/mongod_replicaset/templates/repset_init.j2 dest=/tmp/repset_init.js mode=0777

- name: Initialize the replication set on the primary
  shell: /usr/bin/mongo {{ groups["mongod_primary"][0] }}:{{ mongod_port }}/admin -u admin -p {{ mongo_admin_pass }} /tmp/repset_init.js
  run_once: true
  when: inventory_hostname in groups['mongod_primary']
